# Generated by Django 3.1.2 on 2020-10-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20201026_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
